# Generated by Django 4.2.4 on 2023-09-28 05:06

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_phone_verified",
        ),
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(max_length=4),
        ),
    ]
