# Generated by Django 4.2.4 on 2023-09-28 14:43

import accounts.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_managers_remove_user_is_phone_verified_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.manager.UserManager()),
            ],
        ),
    ]
